services:

  ollama:
    image: ollama/ollama:latest
    container_name: lead-scanner-ollama

    restart: always

    volumes:
      - ollama-data:/root/.ollama

    ports:
      - "11434:11434"


  monitor:
    build: .

    container_name: lead-scanner-monitor

    command: python ./app/main.py

    restart: "no"

    depends_on:
      - ollama

    env_file:
      - .env

    environment:
      OLLAMA_HOST: http://ollama:11434

    volumes:
      - ./config:/app/config
      - ./sessions:/app/sessions


  bot:
    build: .

    container_name: lead-scanner-bot

    command: python ./app/bot.py

    restart: always

    env_file:
      - .env

    volumes:
      - ./config:/app/config


  prometheus:
    image: prom/prometheus
    container_name: lead-scanner-prometheus
    restart: always

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    container_name: lead-scanner-grafana
    restart: always

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus


volumes:
  ollama-data:
  monitor-sessions:
  grafana-data:
